name: Run Citadel Corridor QA Tests

on:
  # For automatic trigger on push
#  push:
#    paths:
#      - 'The Quality Citadel - Quality Assurance/Tier 3/citadel-corridor/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./The Quality Citadel - Quality Assurance/Tier 3/citadel-corridor

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Robot Framework tests
        run: robot saucedemo_suite.robot