name: Run Citadel Corridor QA Tests

on:
  push:
    paths:
      - 'The Quality Citadel - Quality Assurance/Tier 3/citadel-corridor/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./The Quality Citadel - Quality Assurance/Tier 3/citadel-corridor

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Robot Framework tests
        run: robot --variable BROWSER:headlesschrome saucedemo_suite.robot