name: DVC Path Debugger

on:
  workflow_dispatch:

jobs:
  debug-paths:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: List all files in the project directory
        run: ls -lR
        working-directory: "The MLOps Forge - Machine Learning/Tier 3/pipe-bellows"